# Generated by Django 3.2.5 on 2021-07-30 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_product_bought"),
    ]

    operations = [
        migrations.RenameModel(old_name="Product_bought", new_name="Cart"),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField()),
                ("receiver", models.CharField(max_length=100)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=100)),
                ("payment", models.CharField(max_length=100)),
                ("promo", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=100)),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.cart"
                    ),
                ),
            ],
        ),
    ]
