# Generated by Django 3.2.5 on 2021-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210730_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash on delivery'), ('Paypal', 'Paypal'), ('Card', 'Use your credit/debit card')], max_length=20),
        ),
    ]
