# Generated by Django 3.2.5 on 2021-08-03 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("store", "0005_alter_orders_user")]

    operations = [
        migrations.RemoveField(model_name="orders", name="items"),
        migrations.RemoveField(model_name="orders", name="total"),
        migrations.RemoveField(model_name="orders", name="user"),
    ]
