# Generated by Django 3.2.5 on 2021-07-22 03:05

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", models.ImageField(upload_to="images/blogs")),
                ("description", models.TextField()),
                (
                    "url",
                    models.TextField(
                        validators=[django.core.validators.URLValidator()]
                    ),
                ),
            ],
        )
    ]
