# Generated by Django 3.2.5 on 2021-07-23 03:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [("blog", "0002_alter_blog_description")]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        )
    ]
